#!/usr/bin/env python

import sys

def usage():
    print 'Usage: caesar <text>'

def caesar(ct, shift):
    chars = 'abcdefghijklmnopqrstuvwxyz'
    pt = ''
    for c in ct:
        pos = chars.find(c)
        if pos == -1:
            pt += c
        else:
            pt += chars[(pos + shift) % len(chars)]
    return pt

if __name__ == '__main__':
    if len(sys.argv) != 2:
        usage()
        quit()
    else:
        for shift in range(26):
            print caesar(sys.argv[1], shift)
